"use client";
import {useEffect,useState} from "react";
import { API_BASE_URL as API } from "@/utils/apiConfig";
import Cookies from "js-cookie";

type P={_id?:string,name:string,packageType:"You"|"Both",oldPrice:number,price:number,total_connects:number,maxProfileView:number,validDays:number,bestValueSuggestion:boolean,checkedFeatures:string[],uncheckedFeatures:string[],isActive:boolean};
type U=any;
const blank:P={name:"",packageType:"You",oldPrice:0,price:0,total_connects:0,maxProfileView:0,validDays:30,bestValueSuggestion:false,checkedFeatures:[],uncheckedFeatures:[],isActive:true};

export default function Packages(){
 const [p,setP]=useState<P>(blank),[rows,setRows]=useState<P[]>([]),[edit,setEdit]=useState(false),[loading,setLoading]=useState(true);
 const [mobile,setMobile]=useState(""),[user,setUser]=useState<U>(null),[searching,setSearching]=useState(false);
 const [connects,setConnects]=useState(""),[validDays,setValidDays]=useState(""),[note,setNote]=useState("");
 const [history,setHistory]=useState<any>({userSeen:[],othersSeen:[],totalSeen:[]}),[historyTab,setHistoryTab]=useState<"userSeen"|"othersSeen"|"totalSeen">("userSeen"),[message,setMessage]=useState("");
 const [targetConnects,setTargetConnects]=useState("");
 const token=Cookies.get("adminToken")||"";
 const headers={"Content-Type":"application/json","Authorization":`Bearer ${token}`};
 async function load(){setLoading(true);try{const r=await fetch(API+"/api/packages/admin",{headers});const j=await r.json();setRows(j.data||[])}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();const url=edit?API+"/api/packages/"+p._id:API+"/api/packages";const r=await fetch(url,{method:edit?"PUT":"POST",headers,body:JSON.stringify({...p,total_connects:Number(p.total_connects),maxProfileView:Number(p.maxProfileView||p.total_connects)})});const j=await r.json();if(!r.ok){setMessage(j.message||"Unable to save package");return}setMessage("Package saved.");setP(blank);setEdit(false);load()}
 async function remove(id:string){if(!confirm("Delete this package?"))return;await fetch(API+"/api/packages/"+id,{method:"DELETE",headers});load()}
 async function searchUser(){setSearching(true);setMessage("");try{const r=await fetch(API+"/api/packages/admin/search-user?query="+encodeURIComponent(mobile),{headers});const j=await r.json();if(!r.ok)throw new Error(j.message);setUser(j.data);setConnects("");setValidDays(String(j.data?.activePackage?.validTill?30:30));await loadHistory(j.data._id)}catch(e:any){setUser(null);setMessage(e.message||"User not found")}finally{setSearching(false)}}
 async function loadHistory(userId:string){const r=await fetch(API+"/api/packages/admin/phone-history?userId="+userId,{headers});const j=await r.json();if(r.ok)setHistory(j.data||{userSeen:[],othersSeen:[]})}
 async function inject(){if(!user)return;const r=await fetch(API+"/api/packages/manual-inject",{method:"POST",headers,body:JSON.stringify({userId:user._id,connects:Number(connects),validDays:Number(validDays||30),packageId:p._id||undefined,packageType:p.packageType,packageName:p.name,note:note||"Manual package assignment"})});const j=await r.json();setMessage(j.success?"Package/credits assigned successfully.":j.message||"Assignment failed");if(j.success){setUser(j.data);setConnects("");loadHistory(user._id)}}
 async function refund(){if(!user)return;const current=Number(user.connectsBalance||0);const target=Number(targetConnects);if(!Number.isFinite(target)||target<=current){setMessage("Target connect must be greater than the current balance.");return}const amount=target-current;const reason=window.prompt("Refund reason","Closed phone number verified by call");if(!reason)return;const r=await fetch(API+"/api/packages/manual-refund",{method:"POST",headers,body:JSON.stringify({userId:user._id,amount,reason})});const j=await r.json();setMessage(j.success?`Refunded ${amount} credit(s). Current connect: ${target}.`:j.message||"Refund failed");if(j.success){setUser(j.data?.user);setTargetConnects("")}}
 return <main className="min-h-screen bg-[#f1f5f9] p-4 font-sans"><div className="mx-auto max-w-[1400px] space-y-5">
  <div className="bg-white border border-slate-200 px-4 py-3 flex items-center justify-between"><div><h1 className="text-lg font-bold text-black">Package Manager</h1><p className="text-xs text-slate-500">Packages, SSLCommerz credits, Premier Zone and phone-number refund control.</p></div><button onClick={()=>{setP(blank);setEdit(false)}} className="bg-emerald-600 text-white px-4 py-2 text-xs font-bold">+ Add package</button></div>
  <form onSubmit={save} className="bg-white border border-slate-200 p-4"><h2 className="font-bold text-sm mb-3">Create New Package</h2><div className="grid gap-3 md:grid-cols-3 lg:grid-cols-4"><input required placeholder="Package Name (e.g. Gold)" value={p.name} onChange={e=>setP({...p,name:e.target.value})} className="border p-2 text-sm"/><select value={p.packageType} onChange={e=>setP({...p,packageType:e.target.value as P["packageType"]})} className="border p-2 text-sm"><option value="You">You</option><option value="Both">Both</option></select><input type="number" placeholder="Old Price" value={p.oldPrice} onChange={e=>setP({...p,oldPrice:+e.target.value})} className="border p-2 text-sm"/><input required type="number" placeholder="Package Price" value={p.price} onChange={e=>setP({...p,price:+e.target.value})} className="border p-2 text-sm"/><input required type="number" placeholder="Connect / Credit" value={p.total_connects} onChange={e=>setP({...p,total_connects:+e.target.value,maxProfileView:+e.target.value})} className="border p-2 text-sm"/><input required type="number" placeholder="Valid Days" value={p.validDays} onChange={e=>setP({...p,validDays:+e.target.value})} className="border p-2 text-sm"/><input placeholder="Checked features, comma separated" value={p.checkedFeatures.join(", ")} onChange={e=>setP({...p,checkedFeatures:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})} className="border p-2 text-sm md:col-span-2"/><input placeholder="Unchecked features, comma separated" value={p.uncheckedFeatures.join(", ")} onChange={e=>setP({...p,uncheckedFeatures:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})} className="border p-2 text-sm md:col-span-2"/></div><div className="mt-3 flex gap-5 text-xs font-bold"><label><input type="checkbox" checked={p.bestValueSuggestion} onChange={e=>setP({...p,bestValueSuggestion:e.target.checked})}/> Best Value</label><label><input type="checkbox" checked={p.isActive} onChange={e=>setP({...p,isActive:e.target.checked})}/> Active</label></div><div className="mt-4 flex gap-2"><button className="bg-emerald-700 text-white px-5 py-2 text-sm font-bold">{edit?"Update":"Save"}</button>{edit&&<button type="button" onClick={()=>{setP(blank);setEdit(false)}} className="border px-5 py-2 text-sm">Cancel</button>}</div></form>
  <section className="bg-white border border-slate-200 overflow-hidden"><div className="p-3 font-bold text-sm">Existing Packages</div>{loading?<p className="p-5">Loading...</p>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Name</th><th className="p-3">Type</th><th className="p-3">Price</th><th className="p-3">Credits</th><th className="p-3">Valid Days</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{rows.map(x=><tr key={x._id} className="border-t"><td className="p-3 font-bold">{x.name}</td><td className="p-3 text-center">{x.packageType}</td><td className="p-3 text-center">৳{x.price}</td><td className="p-3 text-center">{x.maxProfileView||x.total_connects}</td><td className="p-3 text-center">{x.validDays}</td><td className="p-3 text-center">{x.isActive?"Active":"Inactive"}</td><td className="p-3 text-center"><button onClick={()=>{setP(x);setEdit(true)}} className="mr-2 border px-2 py-1">Edit</button><button onClick={()=>remove(x._id!)} className="border px-2 py-1 text-red-600">Delete</button></td></tr>)}</tbody></table></div>}</section>
  <section className="bg-white border border-slate-200 p-4"><h2 className="font-bold text-sm">Premier Zone — Auto / Manual Package Run</h2><p className="text-xs text-slate-500 mt-1">For users who pay directly to your account when SSLCommerz is not used.</p><div className="mt-3 grid gap-3 md:grid-cols-4"><input value={mobile} onChange={e=>setMobile(e.target.value)} placeholder="Search by email or mobile number" className="border p-2 text-sm"/><button onClick={searchUser} className="bg-slate-900 text-white px-4 py-2 text-sm font-bold">{searching?"Searching...":"Search User"}</button>{user&&<select value={p._id||""} onChange={e=>{const x=rows.find(r=>r._id===e.target.value);if(x)setP(x)}} className="border p-2 text-sm"><option value="">Select Package</option>{rows.filter(x=>x.isActive).map(x=><option key={x._id} value={x._id}>{x.name} — {x.packageType}</option>)}</select>}<input type="number" value={connects} onChange={e=>setConnects(e.target.value)} placeholder="Credits to add" className="border p-2 text-sm"/></div>{user&&<div className="mt-4 rounded border bg-slate-50 p-4"><div className="grid gap-3 md:grid-cols-4 text-xs"><div><b>User</b><p>{user.name}</p></div><div><b>Mobile</b><p>{user.mobile}</p></div><div><b>Current Connect</b><p>{user.connectsBalance||0}</p></div><div><b>Valid To</b><p>{user.activePackage?.validTill?new Date(user.activePackage.validTill).toLocaleDateString():"—"}</p></div></div><div className="mt-3 flex gap-2"><input value={validDays} onChange={e=>setValidDays(e.target.value)} type="number" placeholder="Validity days" className="border p-2 text-sm"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Note" className="border p-2 text-sm flex-1"/><button onClick={inject} className="bg-emerald-600 text-white px-4 py-2 text-xs font-bold">Save / Activate</button><input value={targetConnects} onChange={e=>setTargetConnects(e.target.value)} type="number" min={Number(user.connectsBalance||0)+1} placeholder="Target connect after refund" className="border p-2 text-sm"/>
<a href={user.mobile ? `tel:${user.mobile}` : "#"} className="bg-slate-900 text-white px-4 py-2 text-xs font-bold">Call Verify</a><button onClick={refund} className="bg-amber-600 text-white px-4 py-2 text-xs font-bold">Verify Close + Refund</button></div></div>}</section>
  <section className="bg-white border border-slate-200 p-4"><div className="flex items-center justify-between"><h2 className="font-bold text-sm">Phone View History / Refund Verification</h2>{user&&<div className="flex gap-1"><button onClick={()=>setHistoryTab("userSeen")} className={historyTab==="userSeen"?"bg-emerald-600 text-white px-3 py-1 text-xs":"border px-3 py-1 text-xs"}>User Seen</button>{user?.activePackage?.type==="Both"&&<button onClick={()=>setHistoryTab("othersSeen")} className={historyTab==="othersSeen"?"bg-emerald-600 text-white px-3 py-1 text-xs":"border px-3 py-1 text-xs"}>Others Seen</button>}<button onClick={()=>setHistoryTab("totalSeen")} className={historyTab==="totalSeen"?"bg-emerald-600 text-white px-3 py-1 text-xs":"border px-3 py-1 text-xs"}>Total Seen</button></div>}</div>{!user?<p className="text-xs text-slate-500 mt-4">Search a user above to view who they saw and who saw their numbers.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-2 text-left">Date</th><th className="p-2 text-left">Viewer / Owner</th><th className="p-2 text-left">Post</th><th className="p-2 text-left">Phone</th><th className="p-2 text-left">Status</th><th className="p-2">View</th></tr></thead><tbody>{(history[historyTab]||[]).map((x:any)=><tr key={x._id} className="border-t"><td className="p-2">{new Date(x.createdAt).toLocaleString()}</td><td className="p-2">{historyTab==="userSeen"?x.profileOwnerId?.name+" / "+x.profileOwnerId?.mobile:x.viewerId?.name+" / "+x.viewerId?.mobile}</td><td className="p-2">{x.adId?.headline||"Post"}</td><td className="p-2">{x.adId?.phone||x.postOwner?.mobile||"Hidden"}</td><td className="p-2">{x.status}</td><td className="p-2"><button onClick={()=>{const base=process.env.NEXT_PUBLIC_FRONTEND_URL||"https://currentshadamon.vercel.app"; if(x.adId?._id)window.open(base+"/dashboard?ad="+x.adId._id,"_blank")}} className="border px-2 py-1">View Post</button></td></tr>)}</tbody></table></div>}</section>
  {message&&<div className="fixed bottom-5 right-5 bg-slate-900 text-white px-4 py-3 rounded shadow-xl text-sm">{message}</div>}
 </div></main>
}
